name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Check format
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile API documentation
        run: sbt doc

      - name: Run tests
        run: sbt coverage test

      - name: Generate coverage report
        run: sbt coverageReport

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
