name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        id: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
          cache: sbt

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Check format
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile API documentation
        run: sbt doc

      - name: Run tests
        run: sbt coverage test

      - name: Generate coverage report
        run: sbt coverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish site
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions[bot]@users.noreply.github.com
          sbt "set git.remoteRepo := \"https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git\"" ghpagesPushSite
